sudo: false
git:
  depth: 3
branches:
  only:
  - master
language: node_js
node_js:
- 4
cache:
  directories:
  - node_modules
before_script:
- npm prune
after_success: script/github
env:
  global:
  - DEPLOY_NAME="Travis CI Deployer"
  - DEPLOY_EMAIL="deployer@travis-ci.org"
  - secure: H0RnkLP1BVyFEexJbfbUVcAPL53tAA2SWHEja10M8N8AU6a3co2uJ1oW1Miw7FVZDT1+8qD91355jGO+2ATBV8kbCH9yR/QyLm3+RylcA1Z/i0G2J5fRKOvVY9F2Fk3wDAK43Ph9BbYV25bwpn77RszvnSWmjUPPc2FROsdjc/mnEkkFK/7p/nyOuIqRkpmfvG0Rctl+RdkU3GXa7bKavytG4d9IiUqiiNQfUf1gYRTm0O+twRKq7BJomNr9t9jBQT46FgXGs9fgGiEWWFYJkzoxz8wjjrsiuxzcZ1XOwbHutHXHgaH5m1Zfc6Zr1ceS8b2FzRt/4flH+pm8WqfMjPgngWbXEhqYvN4rVK+9fWeHFLj/w14Pg9CuJMr9xqkMA2ozj/cVeypjzghNBtEZNN5y5W7vAiZXyKPFiqjb3dblhAgwKM/01MR8cE+0g2gUsIgGXGEWoM+GhwEbfTTK+16oSOX32ce8JmlEXZmWt4xgziiIQ2vKwSj46I7gIcEJmp7gUBExqpulx5/nZFPe9bRznl2O8IDRXAQ/cQ8+JWWbBTXhA6P0OfozK+13n29wycv+wD5ORzunjc4B/xAncxZ9iolg50RZae3TyCs61BzpjENVkLXF1d8nbLvevEIziFgM6pdlppxFnwOBvrb+v12FB0QXJlMH6iaC0JvTePE=
  - secure: dPiRWhyo0mNekKcNmBvkp03S5JjwM/seemhJmBAsESXH9LHwTUVIbXgzLBlfcUn2BKYcE40+yjAk/aHdVtBtDuuIcEigNpss9lxZQUEY5/HufxAy5q239u1S17uneLyrEXyjFFTzr9JXXlXZR3dCI9QVzUn9bORR3QIeWPXzKBmQfBLU3vQk0t9VXN5aT6cHjc+cva5E+SO9cjCNxhOsCPxwn8IDullu0r0MkvLvUycCaxg5eCewfYvI0gEwj6PXHRft9FggHebxBVyhutMOW4tjYRT04ObHAHyHKmJsseSdLLp799kzZt0fVAHMdKx+4iI5xKMnLMcIMwU1DKjHZyiuyQ2Sm/BMbfPO2gUapJOJfmidXNab1xXgYFaW5Gp5skm/zHGaIO2cIh8glEf8TxAd8dWbblh0+ET8JPOCAQxWwxKQLHkXrstL7wKpFYebJUw12dmLgdNXFMCeICJXK+FcZKesdB8LT/k2LkfcGEGERBsLaURAs1ux6E0HnTPjBBo0SelJGfcTH5bLrORYVSPAJHk/9HwukH0hF7yepBStMoVIirV7YAVHEE8hkvPWooDucrlJ30DFoPUEa5ira/Nuh84YMpAHLDuQxI4U1I+azqfcjytsLABFYKj3e/Im5bN9osUCks2DOVQorOj784d6ti3dA3hUjAGyBn10Rjk=
