# 2016 January 23
# https://docpad.org/docs/deploy

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - 4
cache:
  directories:
    - node_modules

# Prepare and run our tests
script: "npm test"

# Deployment
after_success: >
  if ([ ! -z "$DEPLOY_TOKEN" ] &&
      [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] &&
      [ -z "$TRAVIS_TAG" ] &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    echo "Deploying";
    git config --global user.email "$DEPLOY_EMAIL";
    git config --global user.name "$DEPLOY_NAME";
    git remote rm origin;
    git remote add origin "https://$DEPLOY_USER:$DEPLOY_TOKEN@github.com/$TRAVIS_REPO_SLUG.git";
    npm run-script deploy;
    echo "Deployed";
  else
    echo "Skipped deploy"
  fi

# Custom Configuration
# travis encrypt --org "DEPLOY_USER=$GITHUB_USERNAME" --add env.global
# travis encrypt --org "DEPLOY_TOKEN=$GITHUB_TRAVIS_TOKEN" --add env.global
env:
  global:
    - DEPLOY_BRANCH="master"  # this is the branch name that you want tested and deployed, set correctly
    - DEPLOY_NAME="Travis CI Deployer"  # this is the name that is used for the deployment commit, set to whatever
    - DEPLOY_EMAIL="deployer@travis-ci.org"  # this is the email that is used for the deployment commit, set to whatever