sudo: false
git:
  depth: 3
branches:
  only:
  - master
language: node_js
node_js:
- 4
cache:
  directories:
  - node_modules
before_script:
- npm prune
after_success: script/github
env:
  global:
  - DEPLOY_NAME="Travis CI Deployer"
  - DEPLOY_EMAIL="deployer@travis-ci.org"
  - secure: K/oEpk5v5gW2sf22d6Gzu2/ZQb5miqLrZOywMQsLNv6lbKM/0gRvMdc0Q39JEYnCFFtqG+lfY2CY6eE7EGz9gWgwOFyFSFNyW9los9VaJ9Hn/J8fdLOIfNIhXeHbfqJLF4W8iA5NqgrFBDP2Pw2BU4MwGPOuVYpjQLbS340AvYfTNdaukubXyjqinmBLnVOEC8Ucxv7piqozzadGxZU2JmLY3LJrkYz+GZuQdNgTEYkZTWGtp6l3OQCkO26AzWjmnlSh6rJpruy2A5L/nJyfCR6vQq6xilbN4id1CHGXB4a/u5nvyuN0DlX1XZ02a1x9f4eXLhtRqpgeQIOlNIam7zDZKPw9a+cn6GypW9Ulec2+ixru4Fbp8MiF+xIlp52CgANyNBmyR1VX1cLE9qQ6ikWVdqMw869A71028jWDwRQihDgIDymOapGaOK2E7Yl0Xd+4JOg1lNL/HoRhRAwYPZlTiNf1AWyIVO2DWnZSdimBnvt+vzUC3mbKSxFOfwdN/89TW6Q5U/SXOatGfpwzkAJeZasmmsoPdPdlsUj9GTA8YOl8muNthCmswrtUMwKgAtNx+AQbe/ieXBxxLxngXBkNGlg2t3ApFwRIukcMejxCUG5fmW/6WAOWGR18GR0FGqSwoiXyUJ9dCpe+e+e5zI9jHrOqj1/6dd7632111u8=
  - secure: dPiRWhyo0mNekKcNmBvkp03S5JjwM/seemhJmBAsESXH9LHwTUVIbXgzLBlfcUn2BKYcE40+yjAk/aHdVtBtDuuIcEigNpss9lxZQUEY5/HufxAy5q239u1S17uneLyrEXyjFFTzr9JXXlXZR3dCI9QVzUn9bORR3QIeWPXzKBmQfBLU3vQk0t9VXN5aT6cHjc+cva5E+SO9cjCNxhOsCPxwn8IDullu0r0MkvLvUycCaxg5eCewfYvI0gEwj6PXHRft9FggHebxBVyhutMOW4tjYRT04ObHAHyHKmJsseSdLLp799kzZt0fVAHMdKx+4iI5xKMnLMcIMwU1DKjHZyiuyQ2Sm/BMbfPO2gUapJOJfmidXNab1xXgYFaW5Gp5skm/zHGaIO2cIh8glEf8TxAd8dWbblh0+ET8JPOCAQxWwxKQLHkXrstL7wKpFYebJUw12dmLgdNXFMCeICJXK+FcZKesdB8LT/k2LkfcGEGERBsLaURAs1ux6E0HnTPjBBo0SelJGfcTH5bLrORYVSPAJHk/9HwukH0hF7yepBStMoVIirV7YAVHEE8hkvPWooDucrlJ30DFoPUEa5ira/Nuh84YMpAHLDuQxI4U1I+azqfcjytsLABFYKj3e/Im5bN9osUCks2DOVQorOj784d6ti3dA3hUjAGyBn10Rjk=
